language: java
jobs:
  include:
    - if: repo = alfasoftware/soapstone
      name: "Test"
      script:
        - git fetch --quiet
        - mvn clean test -B -U
matrix:
  fast_finish: true
  include:
    - jdk: oraclejdk8
